app:
  build: .
  environment:
    - DATABASE_HOST=db
    - DATABASE_PORT=5432
    - DATABASE_USER=postgres
    - RACK_ENV=production
  links:
    - db:db
  ports:
    - 80:9292
db:
  image: postgres:9.4
