app:
  build: .
  environment:
    - DATABASE_HOST=db
    - DATABASE_PORT=5432
    - DATABASE_USER=postgres
    - RAILS_ENV=production
    - RAILS_SERVE_STATIC_FILES=1
  links:
    - db:db
  ports:
    - 80:3000
db:
  image: postgres:9.4
